### PR TITLE
Simulate support for %o in browser

### PR DESCRIPTION
**Pull request by t7tran**

### CODE REVIEW

**Comment by tmpfs** [comment]
Hi @t7tran, I am a bit out of touch with node these days can you please tell me what the `%o` format specifier is used for? Thanks.

**Comment by t7tran** [comment]
We intercept `console.*` methods to capture browser logs. As you know, `console.log()` and its siblings support String Substitution (see **Using string substitutions** in [Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/API/console)). NodeJS's (util.format)[https://nodejs.org/api/util.html#util_util_format_format_args] also supports this specifier.

**Comment by tmpfs** [comment]
Sure I know that, I was asking specifically about `%o` which is new to me. The link you provided indicates they print the object so I guess that is why you are calling `JSON.stringify`.

If you want to squash all your changes into a single commit I'll take a look at merging this.

**Comment by t7tran** [comment]
Done. Thanks for prompt response.

**Comment by tmpfs** [comment]
I think this can be simpler. As `%o` is effectively the same as `%j` we should just let the case statement fall through.

If you delete these lines: 

https://github.com/tmpfs/format-util/pull/5/commits/9a1c9fb4877735ccc0b0d38a2e622a2eadd7dc10#diff-a74e8154a99ee655bfb2c5cb7bcbab0937ba52eda57d3c750646027f07bbc0f8R21-R22

And remove the `tostring` function then the behaviour is the same right?

**Comment by t7tran** [comment]
That was exactly my [first attempt](https://github.com/t7tran/format-util/commit/ff4891031ec95e3ebeaa9ec59d69a75fb748f57a). But it doesn't work for the following:

    format('Error %o', new Error('xyz'));
    format('Error', new Error('xyz'));

`tostring()` is needed for those edge cases.

**Comment by tmpfs** [comment]
> That was exactly my [first attempt](https://github.com/t7tran/format-util/commit/ff4891031ec95e3ebeaa9ec59d69a75fb748f57a). But it doesn't work for the following:
> 
> ```
> format('Error %o', new Error('xyz'));
> format('Error', new Error('xyz'));
> ```
> 
> `tostring()` is needed for those edge cases.

Glad you tried that and thanks for explaining why you choose your approach however that `tostring` function bothers me. Are there other cases apart from `Error` that cannot cleanly be converted using `JSON.stringify`?

If not then I would suggest using `instanceof` instead. I know that people frown on it because it may not point to what you expect but I think in this case it would be fine.

Something like:

```javascript
function toObjectString(arg) {
  if (arg instanceof Error) return arg.toString();
  return JSON.stringify(arg)
}
```

Then the intention of the function becomes much more obvious.

**Comment by t7tran** [comment]
Well, I understand your concern. However, the `Error` is just an illustration of any class implementing `toString()` method. That's why I didn't combine `%o` with `%j`. There might be better ways but using `instanceof` isn't one of them.

**Comment by tmpfs** [comment]
I think that I am willing to support `%o` as an alias to `JSON.stringify` but I don't think special casing is the way to go. If someone wants to format as a string then they can use the `%s` modified for `Error` etc.

**Comment by t7tran** [comment]
It makes perfect sense from `format-util` perspective. It just simply doesn't work in our situation. We will continue with our fork. Closing now.

**Comment by tmpfs** [comment]
I think this is enough to get what you want: https://github.com/tmpfs/format-util/commit/0c989942c959b179eec294a4e725afd63e743f18

Let me know if it works for you and I'll publish a patch version.

**Comment by t7tran** [comment]
Ah, I like that better than my version and appreciate your effort. It definitely makes the library more useful. Could you also add support for remaining args (those without matching specifiers), i.e. for this scenario `format('Error', new Error('xyz'));`? I know that we're retrofitting it into our use cases but the library already supports surplus arguments.

**Comment by tmpfs** [comment]
@t7tran, I don't think we need anymore for trailing arguments as the call to `join()` will coerce them all using `toString()` the only downside is that `JSON.stringify` would be missed for `Array` types but as a format specifier has not been given for the argument I think that is ok. If you see `[object Object]` then you know you need to add a format specifier right?

**Comment by t7tran** [comment]
In our case, we don't have control over the invocations of `console.*` methods.

**Pull request closed without merging**
